from plot_tasks.summ_tasks.summ_plot_pa import summ_plot_pa
from plot_tasks.summ_tasks.summ_plot_k2 import summ_plot_k2
from plot_tasks.summ_tasks.summ_plot_as import summ_plot_as
from plot_tasks.summ_tasks.summ_plot_pj import summ_plot_pj
from plot_tasks.summ_tasks.summ_plot_kj import summ_plot_kj
from plot_tasks.summ_tasks.summ_plot_rj import summ_plot_rj
from plot_tasks.summ_tasks.summ_plot_js import summ_plot_js